version: '3.9'

services:
  # === PostgreSQL Vector ===
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-container
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - backend-network

  # === MinIO ===
  minio:
    image: bitnami/minio:latest
    container_name: minio-container
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@2024
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/bitnami/minio/data
      - ./minio-config:/opt/bitnami/minio/config
    command: minio server /bitnami/minio/data --console-address ":9001"
    networks:
      - backend-network

volumes:
  pgvector-data:
  minio-data:
  minio-config:

networks:
  backend-network:
    driver: bridge