spring:
  application:
    name: cms
  datasource:
    url: jdbc:postgresql://apjf-server.postgres.database.azure.com:5432/cms_db
    username: apjf_admin
    password: PG16password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082